name: cellpose
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - pip=20.0.2=py37_1
  - python=3.7.1
  - setuptools=46.1.3=py37_0
  - wheel=0.34.2=py37_0
  - pip:
    - cellpose==0.0.2.5
    - matplotlib==3.2.1
    - numpy==1.16.6
    - opencv-python==4.2.0.34
    - pandas==1.0.3
    - scikit-image==0.16.2
    - scipy==1.4.1
    - tifffile==2020.2.16

